### ISSUE TITLE
2d build error

### ISSUE THREAD

**Issue by JapeMexDeu** [UG4/plugin_SmallStrainMechanics#1]
The function `MarkAnisotropic_Longest_Scaled_Normal` causes a build error  in the cpp register file small_stain_mech_plugin.cpp line 320 when `cmake -DDIM=2 ..`
This seems to stem from aniso_ref.h line 47
`#ifdef UG_DIM_3`
which makes the function undefined when DIM=2, perhaps the register can be modified accordingly.
The naive fix is to comment out line 320 in small_stain_mech_plugin.cpp to be able to build (of course the provided solmech.lua only works with 3d, but fixing this preserves the provided install instructions of building all plugins).

**Comment by sreiter** [comment]
Hi, thanks for reporting! Maybe it would be a good idea to wrap the registration of that function in an
```
#ifdef UG_DIM_3
  // register here ...
#endif
```
block. A corresponding merge request would be highly appreciated 😃
